version: 2
updates:
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/ovt-fund"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
      production-dependencies:
        patterns:
          - "@heroicons/*"
          - "@headlessui/*"
          - "@omnisat/*"

  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/ovt-program"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "chore"
      include: "scope" 