version: 2
updates:
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/ovt-fund"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
      production-dependencies:
        patterns:
          - "@heroicons/*"
          - "@headlessui/*"
          - "@omnisat/*"
    reviewers:
      - "OTORI-One/developers"
    assignees:
      - "OTORI-One/developers"
    ignore:
      # Don't update Next.js beyond security fixes (to maintain stability)
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
    # Require tests to pass
    require-tests: true

  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/ovt-program"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "OTORI-One/developers"
    assignees:
      - "OTORI-One/developers"
    require-tests: true 